[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

[project]
name = "purchasing-intent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "xgboost",
    "imbalanced-learn",
    "ucimlrepo",
    "matplotlib",
    "seaborn",
    "plotly",
    "dash",
    "kaleido",
    "joblib",
]

[dependency-groups]
dev = [
    "jupyter",
    "ipykernel",
]

[project.scripts]
pi-pipeline = "purchasing_intent.cli:run_pipeline"
